[tool.poetry]
name = "bhashm"
version = "0.1.0"
description = ""
authors = ["Xu Siyuan <inqb@protonmail.com>"]
license = "MIT"
readme = "Readme.md"
packages = [
    {include = "blivedm", from = "src"},
    {include = "bhashm", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = {version = "^3.8.3", extras = ["speedups"]}
aiofiles = "^22.1.0"
aiocsv = "^1.2.3"
rich = "^13.0.0"
pydantic = "^1.10.4"
toml = "^0.10.2"

[tool.poetry.extras]
tinyflux = ["tinyflux"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
