[tool.poetry]
name = "bhashm"
version = "0.1.0"
description = ""
authors = ["Xu Siyuan <inqb@protonmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "blivedm"},
    {include = "bhashm"},
]

[tool.poetry.dependencies]
python = "~3.9"
aiohttp = "3.7.4"
Brotli = "1.0.9"
aiofiles = "^22.1.0"
aiocsv = "^1.2.3"
rich = "^13.0.0"
pydantic = "^1.10.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
